### ISSUE TITLE
Error when installing pdffit2 via conda-forge then running a fit on pdfgui

### ISSUE THREAD

**Issue by 8bitsam** [diffpy/diffpy.pdffit2#18]
```
/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/gui/extendedplotframe.py:182: UserWarning: marker is redundantly defined by the 'marker' keyword argument and the fmt string "." (-> marker='.'). The keyword argument will take precedence.
  curveRef = self.subplot.plot(xData, yData, stylestr, **properties)[0]
Exception in thread Thread-2:
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/control/fitting.py", line 97, in run
    self.fitting.run()
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/control/fitting.py", line 402, in run
    if self.refine_step():
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/control/fitting.py", line 686, in refine_step
    finished =  self.server.refine_step(self.tolerancy)
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdffit2/pdffit.py", line 353, in refine_step
    self.finished = pdffit2.refine_step(self._handle, toler)
SystemError: <built-in function refine_step> returned a result with an exception set
Exception in thread Thread-3:
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/control/fitting.py", line 97, in run
    self.fitting.run()
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/control/fitting.py", line 402, in run
    if self.refine_step():
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdfgui/control/fitting.py", line 686, in refine_step
    finished =  self.server.refine_step(self.tolerancy)
  File "/home/sam/miniconda3/envs/pdffit2_310/lib/python3.10/site-packages/diffpy/pdffit2/pdffit.py", line 353, in refine_step
    self.finished = pdffit2.refine_step(self._handle, toler)
SystemError: <built-in function refine_step> returned a result with an exception set
```

**Comment by 8bitsam** [comment]
Seems to be caused by a problem with the conda-forge build config - the error goes away if building and manually installing the package via pip.

**Comment by sbillinge** [comment]
👍progress...
