### ISSUE TITLE
import issue with diffpy.pdffit2

### ISSUE THREAD

**Issue by briantoby** [diffpy/diffpy.pdffit2#68]
Installing diffpy.pdffit2 via conda results in a package that cannot be loaded. I used this command to create a separate Python interpreter with PDFfit2:
```
conda create -n diffpy.pdffit2_env diffpy.pdffit2 -c conda-forge
```
This installs Py3.12, gsl, pycifrw, diffpy.structure and many more standard packages (such as numpy). 

The package fails to be imported, with the following error:
```
(base) toby@BHT24 /tmp % conda activate diffpy.pdffit2_env
(diffpy.pdffit2_env) toby@BHT24 /tmp % python
Python 3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:32:50) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import diffpy.pdffit2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/G2PY11/envs/diffpy.pdffit2_env/lib/python3.12/site-packages/diffpy/pdffit2/__init__.py", line 25, in <module>
    from diffpy.pdffit2.pdffit import PdfFit
  File "/tmp/G2PY11/envs/diffpy.pdffit2_env/lib/python3.12/site-packages/diffpy/pdffit2/pdffit.py", line 29, in <module>
    from diffpy.pdffit2 import pdffit2
ImportError: cannot import name 'pdffit2' from partially initialized module 'diffpy.pdffit2' (most likely due to a circular import) (/tmp/G2PY11/envs/diffpy.pdffit2_env/lib/python3.12/site-packages/diffpy/pdffit2/__init__.py)
>>> 
```

The same error occurs (with different file paths) if I install diffpy.pdffit2 into the base Python using command
```
conda install  diffpy.pdffit2 -c conda-forge
```

**Comment by sbillinge** [comment]
Thanks for this Brian.

We are right now, as we speak, working on a new release of pdffit2 and pdfgui that brings it up to most recent Python.  We can then address these errors.

**Comment by briantoby** [comment]
This seems to be addressed in diffpy.pdffit2-1.4.3, at least when tested on Intel Mac, but there does not seem to be a osx-arm64 version of diffpy.pdffit2 and the noarch versions are all 1.4.0.

**Comment by sbillinge** [comment]
@briantoby we are working on the arm64.  We hope to have one on pip shortly.  It seems hard to build it on conda-forge.

It would be great if you could help test hat we are doing.   We have a conda-forge pre-release of pdfgui and pdffit2 for python 3.10-3.12:
```
conda install -c conda-forge/label/diffpy.pdfgui_rc -c conda-forge/label/diffpy.pdffit2_rc diffpy.pdfgui=3.1.0rc5 diffpy.pdffit2=1.4.4rc4
```

We should have an arm64 wheel shortly on pip.   I guess you need an arm64 build on conda-forge though, right? @Tieqiong and  @bobleesj are working on these things.

**Comment by briantoby** [comment]
FWIW, I do my builds on GitHub and then push the created packages to conda-forge. An example is here: https://github.com/AdvancedPhotonSource/GSAS-II-buildtools/blob/main/.github/workflows/gsas2pkg.yml

I was never able to get builds on conda-forge to work for me.

**Comment by sbillinge** [comment]
Thanks @briantoby we are kind of working out way back to a similar solution so seeing yours is helpful.  Not quite as the easy back there yet...

**Comment by sbillinge** [comment]
let's test this on the 1.5.0rc release

**Comment by sbillinge** [comment]
closing as completed.  The arm64 issue needs to be tested but that is a different issue and will be tested as part of the overall release protocol.
